app: vjepa_droid
cpus_per_task: 12
folder: /projects/standard/kdesingh/shared/liu03222/ur5e/0421_01/4.8.vjepa2-ac-vitg-256px-8f
mem_per_gpu: 220G
nodes: 1
tasks_per_node: 4
data:
  batch_size: 8
  camera_views:
  - left_mp4_path
  crop_size: 256
  datasets:
    # CSV file, each line is a trajectory dir path
    # See https://github.com/facebookresearch/vjepa2/issues/65
    - /projects/standard/kdesingh/shared/liu03222/ur5_vjepa_0409_action/train_paths.csv
    - /projects/standard/kdesingh/shared/liu03222/ur5_vjepa_0421/train_paths.csv
  dataset_fpcs:
  - 8
  - 8
  holdout_trajectories: 0
  val_clip_ratio: 0.1
  enumerate_clips: true
  clip_stride_frames: 33
  fps: 4
  num_workers: 12
  action_from_state_rotation_mode: rotvec
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 2
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1.0
  - 1.0
  random_resize_scale:
  - 1.0
  - 1.0
  reprob: 0.0
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
meta:
  dtype: bfloat16
  eval_freq: 100
  resume_checkpoint: null
  load_predictor: true
  pretrain_checkpoint: /projects/standard/kdesingh/shared/liu03222/vjepa2_checkpoints/vjepa2-ac-vitg.pt
  context_encoder_key: encoder
  target_encoder_key: encoder
  save_every_freq: 10
  seed: 239
  use_sdpa: true
  use_wandb: true
  wandb_project: vjepa2
  wandb_name: ur5e-vjepa2-ac-vitg-256px-8f
  wandb_mode: online
model:
  model_name: vit_giant_xformers
  pred_depth: 24
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_rope: true
optimization:
  anneal: 15
  epochs: 315
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: null
  lr: 0.000425
  start_lr: 0.000075
  warmup: 15
  weight_decay: 0.04
